title: Anais Guille
logo : /images/pp_rond.png
description: "Portfolio à la croisée des neurosciences et de la data science. Découvrez mes compétences et projets explorant l'intersection entre la recherche scientifique et l'analyse de données."
show_dowloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
css:
  - /assets/css/style.css
nav:
  - title: "Accueil"
    url: /
  - title: "Projets"
    url: /projets/

  
